apiVersion: apps/v1
kind: Deployment
metadata:
  name: newday01
spec:
  selector:
    matchLabels:
      app: newday01-pod
  template:
    metadata:
      labels:
        app: newday01-pod
    spec:
      containers:
      - name: newday01-container
        image: inteltrainingacr01.azurecr.io/newday01:v1
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 5000

      
