name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build_push_image:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        login-server: 'inteltrainingacr01.azurecr.io' # default: index.docker.io
        username: 'inteltrainingacr01'
        password: 'gK4eDUg=Tal8q8oTpvVlOvTHUDkXCV6o'
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag inteltrainingacr01.azurecr.io/newday01:1
      
  deploy:
    runs-on: ubuntu-latest
    needs: build_push_image # Will wait for the execution of the previous job
    
    steps:
    - uses: actions/checkout@v2
    - name: Helm tool installer
      uses: Azure/setup-helm@v1
      with:
        # Version of helm
        version: 3.3.1
    
    - name: Azure Kubernetes set context
      uses: Azure/aks-set-context@v1.1
      with:
        # Azure credentials i.e. output of `az ad sp create-for-rbac --sdk-auth`
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        # Resource Group Name
        resource-group: Intel_RG
        # AKS Cluster Name
        cluster-name: sidlabaks01
    # ... File omitted
    - name: Run Helm Deploy
        helm repo add newday01-api https://github.com/siddharth-dhawan/newday01/blob/master/helm
        helm repo update
      run: >
        helm upgrade --install newday01-api newday01-api
