name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
env:
  HELM_EXPERIMENTAL_OCI: 1
  
jobs:

  build_push_image:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag inteltrainingacr01.azurecr.io/newday01:latest
      
    - name: Azure Container Registry Login  
      uses: Azure/docker-login@v1
      with:
        login-server: 'inteltrainingacr01.azurecr.io' # default: index.docker.io
        username: 'inteltrainingacr01'
        password: 'gK4eDUg=Tal8q8oTpvVlOvTHUDkXCV6o'  
    - name: Push Image  
      run: docker push inteltrainingacr01.azurecr.io/newday01:latest
      
    - name: Helm tool installer
      uses: Azure/setup-helm@v1
      with:
        # Version of helm
        version: 3.3.1
    - name: login to acr using helm
      run: |
        echo $ | helm registry login inteltrainingacr01.azurecr.io --username inteltrainingacr01 --password gK4eDUg=Tal8q8oTpvVlOvTHUDkXCV6o
    - name: Package Helm Chart
      run: helm package ./helm/newday01-api
    - name: save helm chart to local registry
      run: |
        helm chart save /home/runner/work/newday01/newday01/newday01-api-0.1.0.tgz inteltrainingacr01.azurecr.io/charts-newday01-api:latest
    - name: Helm Chart Push
      run: helm chart push inteltrainingacr01.azurecr.io/charts-newday01-api:latest
  
  deploy:
    runs-on: ubuntu-latest
    needs: build_push_image # Will wait for the execution of the previous job
    
    steps:
    - name: Azure Kubernetes set context
      uses: Azure/aks-set-context@v1.1
      with:
        # Azure credentials i.e. output of `az ad sp create-for-rbac --sdk-auth`
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        # Resource Group Name
        resource-group: Intel_RG
        # AKS Cluster Name
        cluster-name: sidlabaks01
    
    - name: Helm tool installer
      uses: Azure/setup-helm@v1
      with:
        # Version of helm
        version: 3.3.1
    - name: login to acr using helm
      run: |
        echo $ | helm registry login inteltrainingacr01.azurecr.io --username inteltrainingacr01 --password gK4eDUg=Tal8q8oTpvVlOvTHUDkXCV6o
    
    - name : Set Helm Env Var
      run : export HELM_EXPERIMENTAL_OCI=1
    - name: Helm Chart Pull
      run: helm chart pull inteltrainingacr01.azurecr.io/charts-newday01-api:latest
      
    - name: Helm Chart Move
      run: helm chart export inteltrainingacr01.azurecr.io/charts-newday01-api:latest --destination ./install
      
    - name: Helm Chart Install
      run: helm upgrade --namespace ns-dev --install --set image.tag=latest newday01-api ./install/newday01-api # release name chart name
     

       
     
#     # ... File omitted
#     - name: AKS Deployment
#       run:
#         kubectl apply -f deployment.yaml
#     - name: AKS Service
#       run:
#         kubectl apply -f service.yaml
        
      
